### ISSUE TITLE
Add API Documentation

### ISSUE THREAD

**Issue by HopefulLlama** [HopefulLlama/JointSCAD#1]
Just use the `README.md`? Perhaps something smarter?

**Comment by probonopd** [comment]
Would be great to have pictures of the joints, so that one can imagine what they do and how they look. Thanks!

**Comment by HopefulLlama** [comment]
Will definitely be adding images of each module.

In the mean time, Wikipedia has some great resources on what they should look like.

**Comment by HopefulLlama** [comment]
Some stuff done as part of commit 99c4566

**Comment by HopefulLlama** [comment]
Added API documentation with screenshots.

Future joints will have documentation and screenshots done under their respective issues.
